### create employee
POST http://ip172-18-0-52-d19rlv8l2o9000d8mcu0-8080.direct.labs.play-with-docker.com/create-employee
Content-Type: application/json

{
    "employee_id": 2,
    "employee_name":"Indal Kumar",
    "employee_designation": "Backend Developer",
    "employee_salery": 100.00
}

### update employee
PUT http://ip172-18-0-52-d19rlv8l2o9000d8mcu0-8080.direct.labs.play-with-docker.com/update-employee
Content-Type: application/json

{
    "employee_id": 1,
    "employee_name":"test",
    "employee_designation": "Golang Developer",
    "employee_salery": 10.00
}

### Get single employees
GET http://ip172-18-0-52-d19rlv8l2o9000d8mcu0-8080.direct.labs.play-with-docker.com/get-employee/2
Content-Type: application/json


### Get all employees
GET http://ip172-18-0-52-d19rlv8l2o9000d8mcu0-8080.direct.labs.play-with-docker.com/get-all-employees
Content-Type: application/json


### Delete employee by employee id
DELETE http://ip172-18-0-52-d19rlv8l2o9000d8mcu0-8080.direct.labs.play-with-docker.com/delete-employee/1
Content-Type: application/json
